
import Duo.connectionprovider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oshad
 */
public class CUSTOMER extends javax.swing.JFrame {

    private int CUSTOMERPK = 0;
    /**
     * Creates new form CUSTOMER
     */
    public CUSTOMER() {
        initComponents();
        setLocationRelativeTo(null);
    }
    private boolean validateFields(){
        if(!TXTN.getText().equals("") && !TXTM.getText().equals("") &&!TXTA.getText().equals(""))
        {
            return false;
        }           
        else   
        {
    return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLCUS = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TXTN = new javax.swing.JTextField();
        TXTM = new javax.swing.JTextField();
        TXTA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BTNS = new javax.swing.JButton();
        BTNU = new javax.swing.JButton();
        BTNR = new javax.swing.JButton();
        BTNC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/blue-abstract-background_1393-339.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 260, -1));

        TBLCUS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "MOBILE", "ADDRESS"
            }
        ));
        TBLCUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLCUSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLCUS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 320, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        TXTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TXTN.setForeground(new java.awt.Color(255, 255, 255));
        TXTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNActionPerformed(evt);
            }
        });
        getContentPane().add(TXTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 300, -1));

        TXTM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TXTM.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 300, -1));

        TXTA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TXTA.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        BTNS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNS.setText("Save");
        BTNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSActionPerformed(evt);
            }
        });
        getContentPane().add(BTNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        BTNU.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNU.setText("Update");
        BTNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUActionPerformed(evt);
            }
        });
        getContentPane().add(BTNU, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        BTNR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNR.setText("Reset");
        BTNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        BTNC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNC.setText("Close");
        BTNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled-3.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TBLCUS.getModel();
        try{
        Connection con = connectionprovider.getCon();
        Statement st =con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM customer");
        while(rs.next()){
            model.addRow(new Object[]{rs.getString("CUSTOMER_ID_pk"),rs.getString("NAME"),rs.getString("MOBILE"),rs.getString("ADDRESS")});
        }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        BTNU.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void TXTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNActionPerformed

    private void BTNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSActionPerformed
        // TODO add your handling code here:
        String NAME= TXTN.getText();
        String MOBILE=  TXTM.getText();
        String ADDRESS= TXTA.getText();
        
        if(validateFields()){
            JOptionPane.showMessageDialog(null,"All Fields Required");
            
        }
        else{
            try{
                Connection con=connectionprovider.getCon();
                PreparedStatement ps= con.prepareStatement("INSERT INTO CUSTOMER (NAME,MOBILE,ADDRESS) VALUES(?,?,?)");
                ps.setString(1,NAME);
                ps.setString(2,MOBILE);
                ps.setString(3,ADDRESS);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Customer Added Successfully");
                setVisible(false);
                new CUSTOMER().setVisible(true);
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_BTNSActionPerformed

    private void BTNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_BTNCActionPerformed

    private void BTNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CUSTOMER().setVisible(true);
    }//GEN-LAST:event_BTNRActionPerformed

    private void TBLCUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLCUSMouseClicked
        // TODO add your handling code here:
        int index = TBLCUS.getSelectedRow();
        TableModel model = TBLCUS.getModel();
        String ID = model.getValueAt(index, 0).toString();
        CUSTOMERPK = Integer.parseInt(ID);
        
        
        
        String NAME =model.getValueAt(index,1).toString();
         TXTN.setText(NAME);
        String MOBILE =model.getValueAt(index,2).toString();
         TXTM.setText(MOBILE);
        String ADDRESS =model.getValueAt(index,3).toString();
         TXTA.setText(ADDRESS);

        BTNS.setEnabled(false);
        BTNU.setEnabled(true);
    }//GEN-LAST:event_TBLCUSMouseClicked

    private void BTNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUActionPerformed
        // TODO add your handling code here:
         String NAME= TXTN.getText();
        String MOBILE=  TXTM.getText();
        String ADDRESS= TXTA.getText();
        
        if(validateFields()){
            JOptionPane.showMessageDialog(null,"All Fields Required");
            
        }
        else{
            try{
                Connection con=connectionprovider.getCon();
                PreparedStatement ps= con.prepareStatement("UPDATE CUSTOMER SET NAME=?,MOBILE=?,ADDRESS=? WHERE CUSTOMER_ID_pk=?");
                ps.setString(1,NAME);
                ps.setString(2,MOBILE);
                ps.setString(3,ADDRESS);
                ps.setInt(4,CUSTOMERPK);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Customer Updated Successfully");
                setVisible(false);
                new CUSTOMER().setVisible(true);
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_BTNUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNC;
    private javax.swing.JButton BTNR;
    private javax.swing.JButton BTNS;
    private javax.swing.JButton BTNU;
    private javax.swing.JTable TBLCUS;
    private javax.swing.JTextField TXTA;
    private javax.swing.JTextField TXTM;
    private javax.swing.JTextField TXTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
