
import javax.swing.JOptionPane;
import java.sql.Connection;
import Duo.connectionprovider;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oshad
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        setLocationRelativeTo(null);
        //if(role.equals("Admin")){
            
        //}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTUN = new javax.swing.JTextField();
        TXTP = new javax.swing.JPasswordField();
        BTNL = new javax.swing.JButton();
        BTNCLO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));
        getContentPane().add(TXTUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 205, -1));
        getContentPane().add(TXTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 205, -1));

        BTNL.setText("LOGIN");
        BTNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLActionPerformed(evt);
            }
        });
        getContentPane().add(BTNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 150, 40));

        BTNCLO.setText("CLOSE");
        BTNCLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCLOActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCLO, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 140, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LOGIN.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLActionPerformed
       String userRole =TXTUN.getText();
       String password =TXTP.getText();
       
       int temp=0;
       try{
       Connection con = connectionprovider.getCon();
       Statement st = con.createStatement();
       ResultSet rs=st.executeQuery("select * from appuser where userRole='"+userRole+"' and password='"+password+"'");
       while(rs.next()){
           temp=1;
           setVisible(false);
           new HOME(rs.getString("userRole")).setVisible(true);
       }
       if(temp==0){JOptionPane.showMessageDialog(null,"Incorrect USERNAME OR PASSWORD");}
               }
       catch(Exception e)
       {JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_BTNLActionPerformed

    private void BTNCLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCLOActionPerformed
int a=JOptionPane.showConfirmDialog(null,"Do You Want To Exit","select",JOptionPane.YES_NO_OPTION);
if(a==0){ 
    System.exit(0);
}
    }//GEN-LAST:event_BTNCLOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCLO;
    private javax.swing.JButton BTNL;
    private javax.swing.JPasswordField TXTP;
    private javax.swing.JTextField TXTUN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
