
import Duo.connectionprovider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;import javax.swing.table.TableModel;
;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oshad
 */
public class MANAGECATEGORY extends javax.swing.JFrame {

    private int CATEGORY_ID_pk = 0;
    /**
     * Creates new form MANAGECATEGORY
     */
    public MANAGECATEGORY() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private boolean validateFields(){
        if(TXTN.getText().equals("")){
            return false;
        }
        else{
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLEC = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TXTN = new javax.swing.JTextField();
        BTNS = new javax.swing.JButton();
        BTNU = new javax.swing.JButton();
        BTNR = new javax.swing.JButton();
        BTNC = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE CATEGORY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 36));

        TABLEC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLECMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLEC);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 352, 420));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 116, -1));
        getContentPane().add(TXTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 300, -1));

        BTNS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNS.setText("Save");
        BTNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSActionPerformed(evt);
            }
        });
        getContentPane().add(BTNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        BTNU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNU.setText("Update");
        BTNU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUActionPerformed(evt);
            }
        });
        getContentPane().add(BTNU, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        BTNR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNR.setText("Reset");
        BTNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        BTNC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNC.setText("Close");
        BTNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        btndel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndel.setText("Delete");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 310, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Untitled-3.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TABLEC.getModel();
        try{
        Connection con = connectionprovider.getCon();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from category");
        while(rs.next()){
            model.addRow(new Object[]{rs.getString("CATEGORY_ID_PK"),rs.getString("NAME")});
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        BTNU.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void BTNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSActionPerformed
        // TODO add your handling code here:
     String NAME = TXTN.getText();
     String CATEGORY_ID_pk = txtid.getText();

       // if (validateFields()){
       //    JOptionPane.showMessageDialog(null, "ALL FIELDS ARE REQUIRED");
    //}
        //else{
          try{
                Connection con = connectionprovider.getCon();
                PreparedStatement ps = con.prepareStatement("insert into CATEGORY (CATEGORY_ID_pk,NAME) values(?,?)");
                ps.setString(1,CATEGORY_ID_pk);
                ps.setString(2,NAME);
                      // ps.setInt(1 ,CATEGORY_ID_pk);
                
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Category Added Successfully");
                        setVisible(false);
                        new MANAGECATEGORY().setVisible(true);
           }
          catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
          }
       // }
    }//GEN-LAST:event_BTNSActionPerformed

    private void BTNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_BTNCActionPerformed

    private void BTNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MANAGECATEGORY().setVisible(true);
    }//GEN-LAST:event_BTNRActionPerformed

    private void TABLECMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLECMouseClicked
        // TODO add your handling code here:
        int index = TABLEC.getSelectedRow();
        TableModel model = TABLEC.getModel();
        String ID = model.getValueAt(index, 0).toString();
        CATEGORY_ID_pk = Integer.parseInt(ID);
        
        
        
        String NAME =model.getValueAt(index,1).toString();

        TXTN.setText(NAME);
        txtid.setText(ID);
        BTNS.setEnabled(false);
        BTNU.setEnabled(true);
        
    }//GEN-LAST:event_TABLECMouseClicked

    private void BTNUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUActionPerformed
        // TODO add your handling code here:
        
             String NAME = TXTN.getText();

       // if (validateFields()){
       //    JOptionPane.showMessageDialog(null, "ALL FIELDS ARE REQUIRED");
    //}
        //else{
          try{
                Connection con = connectionprovider.getCon();
                PreparedStatement ps = con.prepareStatement("UPDATE CATEGORY SET NAME=? WHERE CATEGORY_ID_pk=?");
                ps.setString(1,NAME);
               ps.setInt(2 ,CATEGORY_ID_pk);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Category Updated Successfully");
                        setVisible(false);
                        new MANAGECATEGORY().setVisible(true);
           }
          catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
          }
       // }
    }//GEN-LAST:event_BTNUActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
          try{
                Connection con = connectionprovider.getCon();
                PreparedStatement ps = con.prepareStatement("DELETE  CATEGORY_ID_pk,NAME FROM CATEGORY");
                //PreparedStatement pa = con.prepareStatement("DELETE CATEGORY_ID_pk , NAME FROM CATEGORY INNER JOIN PRODUCTS WHERE CATEGORY.CATEGORY_ID_pk= PRODUCT.CATEGORY_ID_fk and CATEGORY.CATEGORY_ID_pk= '?'");
                        ps.executeUpdate();
                        //pa.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Category Deleted Successfully");
                        setVisible(false);
                        new MANAGECATEGORY().setVisible(true);
           }
          catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
          }
    }//GEN-LAST:event_btndelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGECATEGORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGECATEGORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGECATEGORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGECATEGORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGECATEGORY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNC;
    private javax.swing.JButton BTNR;
    private javax.swing.JButton BTNS;
    private javax.swing.JButton BTNU;
    private javax.swing.JTable TABLEC;
    private javax.swing.JTextField TXTN;
    private javax.swing.JButton btndel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
