
import Duo.connectionprovider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oshad
 */
public class ORDER extends javax.swing.JFrame {

    private int CUSTOMERPK=0;
    private int PRODUCTPK=0;
    private int FINALTOTALPRICE=0;
    private String ORDERID="";
    /**
     * Creates new form ORDER
     */
    public ORDER() {
        initComponents();
        setLocationRelativeTo(null);
    }
private void CLEARPRODUCTFIELDS(){
    PRODUCTPK=0;
    TXTPN.setText("");
    TXTPP.setText("");
    TXTQ.setText("");
}

public String GETUNIQUEID(String prefix){
    return prefix+System.nanoTime();
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBLCL = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBLPL = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBLOL = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BTNS = new javax.swing.JButton();
        BTNR = new javax.swing.JButton();
        BTNC = new javax.swing.JButton();
        TXTPN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTPP = new javax.swing.JTextField();
        TXTQ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXTN = new javax.swing.JTextField();
        TXTM = new javax.swing.JTextField();
        TXTA = new javax.swing.JTextField();
        LBLST = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TBLCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "MOBILE", "ADDRESS"
            }
        ));
        TBLCL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLCLMouseClicked(evt);
            }
        });
        TBLCL.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TBLCLComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(TBLCL);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 299, 224));

        TBLPL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBLPL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLPLMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TBLPL);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 138, 300, 224));

        TBLOL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TBLOL);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 138, 300, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 443, -1, -1));

        BTNS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNS.setText("Save");
        BTNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSActionPerformed(evt);
            }
        });
        getContentPane().add(BTNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 130, -1));

        BTNR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNR.setText("Reset");
        BTNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNR, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 130, -1));

        BTNC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTNC.setText("Close");
        BTNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCActionPerformed(evt);
            }
        });
        getContentPane().add(BTNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 130, -1));

        TXTPN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(TXTPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 240, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selected product:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 526, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 610, -1, -1));

        TXTPP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(TXTPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 240, -1));

        TXTQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(TXTQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 240, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 610, -1, -1));

        TXTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(TXTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 240, -1));

        TXTM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(TXTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 240, -1));

        TXTA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(TXTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 240, -1));

        LBLST.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        LBLST.setForeground(new java.awt.Color(255, 255, 255));
        LBLST.setText("Total Amount:");
        getContentPane().add(LBLST, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 110, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, 240, -1));

        jLabel9.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel9.setText("ORDER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 230, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/1920x1080-blue-solid-color-background.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-520, 0, 1530, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_BTNSActionPerformed

    private void BTNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ORDER().setVisible(true);
        
    }//GEN-LAST:event_BTNRActionPerformed

    private void BTNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_BTNCActionPerformed

    private void TBLCLComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TBLCLComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_TBLCLComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
               TXTN.setEditable(false);
         TXTM.setEditable(false);
          TXTA.setEditable(false);
          
          TXTPN.setEditable(false);
          TXTPP.setEditable(false);
          
          
          DefaultTableModel model=(DefaultTableModel)TBLCL.getModel();
          DefaultTableModel productModel=(DefaultTableModel)TBLPL.getModel();
          
          try
          {
          Connection con=connectionprovider.getCon();
          Statement st=con.createStatement();
          ResultSet rs= st.executeQuery("SELECT * FROM CUSTOMER");
                  while(rs.next()){
                         model.addRow(new Object[]{rs.getString("CUSTOMER_ID_pk"),rs.getString("NAME"),rs.getString("MOBILE"),rs.getString("ADDRESS")});
                  }
          
          rs=st.executeQuery("SELECT * FROM PRODUCT inner join CATEGORY on product.CATEGORY_ID_fk = CATEGORY.CATEGORY_ID_pk");
          while(rs.next()){
               productModel.addRow(new Object[]{rs.getString("PRODUCT_ID_pk"),rs.getString("SIZE"),rs.getString("QUANTITY"),rs.getString("PRICE"),rs.getString("CATEGORY_ID_fk"),rs.getString(2)});
          }
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(null, e);
          }
    }//GEN-LAST:event_formComponentShown

    private void TBLCLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLCLMouseClicked
        // TODO add your handling code here:
                int index = TBLCL.getSelectedRow();
        TableModel model = TBLCL.getModel();
        String ID = model.getValueAt(index, 0).toString();
        CUSTOMERPK = Integer.parseInt(ID);
        
        
        
        String NAME =model.getValueAt(index,1).toString();
         TXTN.setText(NAME);
        String MOBILE =model.getValueAt(index,2).toString();
         TXTM.setText(MOBILE);
        String ADDRESS =model.getValueAt(index,3).toString();
         TXTA.setText(ADDRESS);

   
    }//GEN-LAST:event_TBLCLMouseClicked

    private void TBLPLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLPLMouseClicked
        // TODO add your handling code here:
                        int index = TBLPL.getSelectedRow();
        TableModel model = TBLPL.getModel();
        String ID = model.getValueAt(index, 0).toString();
        PRODUCTPK = Integer.parseInt(ID);
        
        
        
        String SIZE =model.getValueAt(index,1).toString();
         TXTPN.setText(SIZE);
        String PRICE =model.getValueAt(index,2).toString();
         TXTPP.setText(PRICE);

    }//GEN-LAST:event_TBLPLMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String NoOfUnits= TXTQ.getText();
        if
                (!NoOfUnits.equals("")){
            String PRODUCTNAME = TXTPN.getText();
            String PRODUCTPRICE=TXTPP.getText();
            
            int TOTALPRICE = Integer.parseInt(TXTQ.getText()) * Integer.parseInt(PRODUCTPRICE);
            int CHECKSTOCK = 0;
            int CHECKPRODUCTALREADYEIST = 0;
            try{
               Connection con = connectionprovider.getCon();
        Statement st =con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM PRODUCT_PK="+ PRODUCTPK +""); 
        while(rs.next()){
            if(rs.getInt("QUANTITY")>=Integer.parseInt(NoOfUnits)){
            CHECKSTOCK=1;
            }
            else{
                JOptionPane.showMessageDialog(null,"Product Not Available"+rs.getInt("QUANTITY")+"Left");
            }
        }           
            }       
        catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                }
            if(CHECKSTOCK ==1 ){
                DefaultTableModel model=(DefaultTableModel) TBLOL.getModel();
                if(TBLOL.getRowCount() !=0){
                    for(int i=0; i<TBLOL.getRowCount();i++){
                        if(Integer.parseInt(model.getValueAt(i,0).toString())==PRODUCTPK){
                            CHECKPRODUCTALREADYEIST=1;
                            JOptionPane.showMessageDialog(null,"Product Already Exist");
                            
                        }
                    }
                }
                if(CHECKPRODUCTALREADYEIST==0){
                    model.addRow(new Object[]{PRODUCTPK,PRODUCTNAME,NoOfUnits,PRODUCTPRICE,TOTALPRICE});
                    FINALTOTALPRICE =FINALTOTALPRICE + TOTALPRICE ;
                    LBLST.setText(String.valueOf(FINALTOTALPRICE));
                    JOptionPane.showMessageDialog(null,"Added Successfully");
                }
                CLEARPRODUCTFIELDS();
            }
        } else
         {
            JOptionPane.showMessageDialog(null,"No of Quantity and Product Required");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ORDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ORDER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNC;
    private javax.swing.JButton BTNR;
    private javax.swing.JButton BTNS;
    private javax.swing.JLabel LBLST;
    private javax.swing.JTable TBLCL;
    private javax.swing.JTable TBLOL;
    private javax.swing.JTable TBLPL;
    private javax.swing.JTextField TXTA;
    private javax.swing.JTextField TXTM;
    private javax.swing.JTextField TXTN;
    private javax.swing.JTextField TXTPN;
    private javax.swing.JTextField TXTPP;
    private javax.swing.JTextField TXTQ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
